dist: xenial
language: python

env:
  global:
    - PYTEST_ADDOPTS="-vv --cov --cov-report=xml"

jobs:
  include:
    - os: windows
      language: shell
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=py37-coverage
      before_install:
        - choco install --no-progress python

    - python: '3.7'
      env: TOXENV=py37-coverage

install:
  - pip install tox==3.12.1
  # NOTE: need to upgrade virtualenv to allow "Direct url requirement" with
  # installation in tox.
  - pip install virtualenv==16.6.0

script:
  - tox

after_script:
  - |
    if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
      bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n $TOXENV -F "${TRAVIS_OS_NAME}"
    fi

# Only master and releases.  PRs are used otherwise.
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
