dist: xenial
language: python

env:
  global:
    - PYTEST_ADDOPTS="-vv --cov --cov-report=xml"

jobs:
  include:
    - os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOXENV=py38-coverage
      before_install:
        - choco install --no-progress python

    - os: osx
      osx_image: xcode10.2
      language: generic
      env: TOXENV=py37-coverage
      before_install:
        - ln -sfn "$(which python3)" /usr/local/bin/python
        - python -V
        - test $(python -c 'import sys; print("%d%d" % sys.version_info[0:2])') = 37

    - python: '2.7'
      env: TOXENV=py27-coverage
    - python: '3.4'
      env: TOXENV=py34-coverage
    - python: '3.5'
      env: TOXENV=py35-coverage
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.7'
      env: TOXENV=py37-coverage
    - python: '3.8-dev'
      env: TOXENV=py38-coverage
    - python: 'pypy'
      env: TOXENV=pypy-coverage
    - python: 'pypy3'
      env: TOXENV=pypy3-coverage

    - python: '3.7'
      env: TOXENV=checkqa

install:
  - pip install tox==3.12.1
  # NOTE: need to upgrade virtualenv to allow "Direct url requirement" with
  # installation in tox.
  - pip install virtualenv==16.6.0

script:
  - tox

after_script:
  - |
    if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
      curl --version
      bash <(wget https://codecov.io/bash -O -) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n $TOXENV -F "${TRAVIS_OS_NAME}"
    fi

# Only master and releases.  PRs are used otherwise.
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
